### ISSUE TITLE
Feedbackのリンクは別ウィンドウの方が嬉しいかも

### ISSUE THREAD

**Issue by den8** [kami-zh/repost#2]
githubへのリンクになるので、アプリに戻りたい時に不便でした。

**Comment by kami-zh** [comment]
変更します!! 👍 👍 👍

**Comment by kami-zh** [comment]
対応しました!!
https://github.com/kami-zh/repost/commit/63119a9a2186bf4cfd39e3fc7c16b22c2de74963
