### ISSUE TITLE
アバタ―登録画面について

### ISSUE THREAD

**Issue by ymzkryo** [kami-zh/repost#23]
アバタ―アップデート時に   

- - imgのフォーマットが表示されていない

1. サイズ
2. ファイルタイプ

- ローカルから画像を選択しても"Update"ボタンをクリックするまでどの画像を選択したか反映されない

の2点が気になりました。  
初回アバタ―登録時にちょっと戸惑いがありました。

**Comment by zenizh** [comment]
ありがとうございます！
プレビューについては対応完了しました。
サイズ・ファイルタイプについてはこれから対応します 👍

**Comment by zenizh** [comment]
アップロード内容の検証は用いているライブラリが現状対応していないようなので別issueで管理します！
ご報告ありがとうございました 🙌
