### ISSUE TITLE
プレビュー画面と本番の投稿の文字の色が違う(マークダウン)

### ISSUE THREAD

**Issue by ryosuke-endo** [kami-zh/repost#24]
## 内容

[![https://gyazo.com/15ad144ab87206ecd5d5c2e26caa3575](https://i.gyazo.com/15ad144ab87206ecd5d5c2e26caa3575.png)](https://gyazo.com/15ad144ab87206ecd5d5c2e26caa3575)

文字が赤色になっている

[![https://gyazo.com/f43c08924657eade6beb37b1f19457bd](https://i.gyazo.com/f43c08924657eade6beb37b1f19457bd.png)](https://gyazo.com/f43c08924657eade6beb37b1f19457bd)

色が変更されてない。

マークダウンのparseがうまくいっていない？

**Comment by zenizh** [comment]
ありがとうございます！
バックエンドとフロントエンドでMarkdownのパーサが異なるので、そのあたり差異が生じてしまっています。
対応します 👍

**Comment by zenizh** [comment]
修正しました！

**Comment by ryosuke-endo** [comment]
ありがとうございます！
