### ISSUE TITLE
一般ユーザなのに Create/Edit a channel できそうなUIになっている

### ISSUE THREAD

**Issue by den8** [kami-zh/repost#3]
実際には作成、更新はできないが、ツールチップが出ていてできそうな感じになっているので表示させないようにするのが良いかもしれないです。

**Comment by kami-zh** [comment]
ありがとうございます!! 対応します 🔥

**Comment by kami-zh** [comment]
解決しました!! https://github.com/kami-zh/repost/commit/83070e4952ae61ceace0d4497ea54f7e79a4f9b8
